baseURL = "https://kluctl-hugo-new.netlify.app/"
title = "kluctl.io"
# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true
paginate = 5
# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["lotusdocs"]

[module]
    # uncomment line below for temporary local development of module
    # or when using a 'theme' as a git submodule
    # replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    # [[module.imports]]
    #     path = "github.com/colinwilson/lotusdocs"
    #     disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

    [[module.mounts]]
        source = 'assets'
        target = 'assets'
    
    [[module.mounts]]
        source = 'static/images/blog'
        target = 'assets/images/blog'
    
    [[module.mounts]]
        source = 'static/images/webui'
        target = 'assets/images/webui'

[menu]
# Links in the header (main menu)
[[menu.main]]
    name  = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    name  = "Blog"
    url = "/blog"
    weight = 20

[[menu.main]]
    name  = "Community"
    url = "/community"
    weight = 30

# Links in the footer
[[menu.footer]]
    name  = "Home"
    url = "/"
    weight = 10

[[menu.footer]]
    name  = "Docs"
    url = "/docs"
    weight = 20

[[menu.footer]]
    name  = "Blog"
    url = "/blog"
    weight = 30

[[menu.footer]]
    name  = "Community"
    url = "/community"
    weight = 40

[[menu.footer]]
    name  = "Privacy policy"
    url = "/privacy"
    weight = 50

# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to enable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]


# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 95
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "kluctl.io"
description = "The missing glue to put together large Kubernetes deployments."
languageName ="English"
# Weight used for sorting.
weight = 1


# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "RSS"]

[params]
copyright = "The Kluctl Authors"
privacy_policy = "https://kluctl.io/privacy"

# First one is picked as the Twitter card image if not set on page.
images = ["images/card.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://kluctl.io"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/kluctl/www-kluctl.io"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/kluctl/kluctl"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
# github_branch= "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "d72aa9b2712488cc3"

    [params.docs] # Parameters for the /docs 'template'
        title           = "Lotus Docs Example Site"           # default html title for documentation pages/sections

        # pathName        = "docs"                            # path name for documentation site | default "docs"

        themeColor      = "emerald"                            # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan

        darkMode        = true                                # enable dark mode option? default false

        prism           = true                                # enable syntax highlighting via Prism

        prismTheme      = "lucario"                           # (optional) - Set theme for PrismJS. Options include: lotusdocs (default), solarized-light, twilight, lucario

        # gitinfo
        repoURL         = "https://github.com/colinwilson/lotusdocs.dev"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
        repoBranch      = "release"
        editPage        = true                                # enable 'Edit this page' feature - default false
        lastMod         = true                                # enable 'Last modified' date on pages - default false
        lastModRelative = true                                # format 'Last modified' time as relative - default true

        sidebarIcons    = false                                # enable sidebar icons? default false
        breadcrumbs     = true                                # default is true
        backToTop       = true                                # enable back-to-top button? default true

        # ToC
        toc             = true                                # enable table of contents? default is true
        tocMobile       = true                                # enable table of contents in mobile view? default is true
        scrollSpy       = true                                # enable scrollspy on ToC? default is true

        # front matter
        descriptions    = true                                # enable front matter descriptions under content title?
        titleIcon       = false                               # enable front matter icon title prefix? default is false

        # content navigation
        navDesc         = true                                # include front matter descriptions in Prev/Next navigation cards
        navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

        listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description

        # Link behaviour
        intLinkTooltip  = true                                # Enable a tooltip for internal links that displays info about the destination? default false
        # extLinkNewTab   = false                               # Open external links in a new Tab? default true

    [params.flexsearch] # Parameters for FlexSearch
        enabled             = true
        # tokenize            = "full"
        # optimize            = true
        # cache               = 100
        # minQueryChar        = 3 # default is 0 (disabled)
        # maxResult           = 5 # default is 5
        # searchSectionsIndex = []

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# Configurations for CTA and footer sections
[params.footer]
    # CTA section
    cta = "Ready to Solve Your Deployment Issues?"
    button_text = "Get started"
    button_link = "/docs"

    # footer section
    logo = "icons/logo-white.svg" # relative to the assets folder
    tagline = "Kluctl is the missing glue to put together large Kubernetes deployments."
    links_heading = "Links"
    copyright_text = "The Kluctl Authors. All Rights Reserved."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
